### ISSUE TITLE
Ommiting diacritic/special characters

### ISSUE THREAD

**Issue by krkabol** [Mistralys/text-diff#1]
hello, 
using PHP 7.4.2 & text-diff 2.0.0 I reach a result where some special characters are committed:

`$diff = Diff::compareStrings("Géhu – jun02 (LM).", "Géhu et al. 1984 (31) – jun02 (LM).", true);`
`$diff->toHTML());`

results in 

> Ghu et al. 1984 (31) jun02 (LM).

with correctly marked del/ins, but missing the "é" and "–" characters.
thank you in advance for your advice
Petr Novotný

**Comment by Mistralys** [comment]
@krkabol, thanks - I am still on holiday right now. I will have a look next week.

**Comment by krkabol** [comment]
@Mistralys works well, thank you!

**Comment by Mistralys** [comment]
You're welcome - thanks for reporting :D
