### ISSUE TITLE
composer autoload

### ISSUE THREAD

**Issue by miklosban** [Mistralys/text-diff#3]
Hi,

I try to use this package, but can't load somehow...
That I'm did:

composer require mistralys/text-diff

It is done successfully

In my code there is a

require_once( 'vendor/autoload.php');

It works, other packages loaded correctly.

I try to use text-diff in this way:

Diff::compareFiles(...

Got error:
PHP Fatal error:  Uncaught Error: Class 'Diff' not found  ...

I tried to load class:
$Diff = new Diff();

Same error...

Finally, following the namespace in the Diff.php, I tried this:
$Diff = new Mistralys\Diff\Diff;

But it only works if I pass two string arguments according to the _construct function.
So, I modified, it and I could to create a working code, but it is very ugly.

    $Diff = new Mistralys\Diff\Diff('','');
    $d = $Diff->compareFiles($file1, $file2);
    echo $d->toHTMLTable();

How can I use it in a better way?

**Comment by miklosban** [comment]
Okay, I found the solution:

use Mistralys\Diff\Diff;
...
$d = $Diff->compareFiles($file1, $file2);
echo $d->toHTMLTable();

**Comment by Mistralys** [comment]
Hi @miklosban,

Yes, the `use Mistralys\Diff\Diff;` handles loading the class so it is available in your script. You have to add this in all files where you wish to use a `Diff::` call.

Tip: If you use a PHP IDE like PHPStorm, it recognizes all classes and will automatically add `use` statements when they are needed. If I remember correctly, they have a free version available.

I updated the readme to clarify.
